<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="catArticulo.aspx.cs" Inherits="CapaPresentacion.catArticulo1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <div class="container">
            <div ><h2>Catalogo artículos</h2></div>
    

        <div class="form-group">
            <label>Código artículo bodega</label>            
            <input type="number" id="txtCodigoArticulo" runat="server" class="form-control" placeholder="Código artículo bodega" />
        </div>
        <div class="form-group">
            <label>Nombre artículo </label>
            <asp:TextBox ID="txtNombreArticulo" runat="server" placeholder="Nombre artículo" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Id categoría</label>
            <asp:TextBox ID="txtIdCategoria" runat="server" placeholder="Id categoría" CssClass="form-control"></asp:TextBox>
        </div>
      

        <asp:GridView ID="dtgCatArt" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="codigoArticulo" DataSourceID="catArt" CssClass="table table-bordered" AllowSorting="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#CCCCCC" />
        <Columns>
            <asp:BoundField DataField="codigoArticulo" HeaderText="Código Articulo" ReadOnly="True" SortExpression="codigoArticulo" />
            <asp:BoundField DataField="nombreArticulo" HeaderText="Nombre Artículo" SortExpression="nombreArticulo" />
            <asp:BoundField DataField="idCategoria" HeaderText="Id Categoría" SortExpression="idCategoria" />
        </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
    </asp:GridView>
    <asp:SqlDataSource ID="catArt" runat="server" ConnectionString="<%$ ConnectionStrings:VentaComputadorasConnectionString11 %>" SelectCommand="SELECT * FROM [catArticulos]" DeleteCommand="Delete From [catArticulos] Where [codigoArticulo] = @codigoArticulo" UpdateCommand="UPDATE [catArticulos] SET [codigoArticulo] = @codigoArticulo, [nombreArticulo] = @nombreArticulo, [idCategoria] = @idCategoria"></asp:SqlDataSource>
        <asp:Button ID="btnGuardarCatArt" runat="server" Text="Guardar" OnClick="btnGuardar_Click" CssClass="btn btn-primary" />
        </div>
</asp:Content>
