<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="catalogos.aspx.cs" Inherits="CapaPresentacion.catArticulo" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    
        <div class="container">
            <div ><h2>Catalogo artículos</h2></div>
    

        <div class="form-group">
            <label>Código artículo bodega</label>            
            <input type="number" id="txtCodigoArticulo" runat="server" class="form-control" placeholder="Código artículo bodega" />
        </div>
        <div class="form-group">
            <label>Nombre artículo </label>
            <asp:TextBox ID="txtNombreArticulo" runat="server" placeholder="Nombre artículo" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Id bodega</label>
            <asp:TextBox ID="txtIdCategoria" runat="server" placeholder="Id bodega" CssClass="form-control"></asp:TextBox>
        </div>
      

        <asp:GridView ID="dtgCatArt" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="codigoArticulo" DataSourceID="catArt" CssClass="table table-bordered" AllowSorting="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#CCCCCC" />
        <Columns>
            <asp:BoundField DataField="codigoArticulo" HeaderText="Código Articulo" ReadOnly="True" SortExpression="codigoArticulo" />
            <asp:BoundField DataField="nombreArticulo" HeaderText="Nombre Artículo" SortExpression="nombreArticulo" />
            <asp:BoundField DataField="idCategoria" HeaderText="Id Categoría" SortExpression="idCategoria" />
        </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
    </asp:GridView>
    <asp:SqlDataSource ID="catArt" runat="server" ConnectionString="<%$ ConnectionStrings:VentaComputadorasConnectionString11 %>" SelectCommand="SELECT * FROM [catArticulos]" DeleteCommand="Delete From [catArticulos] Where [codigoArticulo] = @codigoArticulo" UpdateCommand="UPDATE [catArticulos] SET [codigoArticulo] = @codigoArticulo, [nombreArticulo] = @nombreArticulo, [idCategoria] = @idCategoria"></asp:SqlDataSource>
        <asp:Button ID="btnGuardarCatArt" runat="server" Text="Guardar" OnClick="btnGuardar_Click" CssClass="btn btn-primary" />
        </div>

    <%--Catálogo de empleados--%>


    <div class="container">
            <div ><h2>Catalogo empleados</h2></div>
    

        <div class="form-group">
            <label>Código empleado</label>
            <asp:TextBox ID="txtCodEmpleado" runat="server" CssClass="form-control" placeholder="Código empleado"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Nombre empleado </label>
            <asp:TextBox ID="txtNombreEmpleado" runat="server" placeholder="Nombre empleado" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Primer apellido</label>
            <asp:TextBox ID="txtPrimerApellido" runat="server" placeholder="Primer apellido" CssClass="form-control"></asp:TextBox>
        </div>
         <div class="form-group">
            <label>Segundo apellido</label>
            <asp:TextBox ID="txtSegundoApellido" runat="server" placeholder="Segundo apellido" CssClass="form-control"></asp:TextBox>
        </div>
      
        <asp:Button ID="btnGuardarEmpleado" CssClass="btn btn-primary" runat="server" Text="Guardar" OnClick="btnGuardarEmpleado_Click" />

        <asp:GridView ID="dtgCatEMpleados" CssClass="table table-bordered" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" DataKeyNames="codigoEmpleado" DataSourceID="catEmpleados" ForeColor="Black" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
                <asp:BoundField DataField="codigoEmpleado" HeaderText="Código empleado" ReadOnly="True" SortExpression="codigoEmpleado" />
                <asp:BoundField DataField="nombreEmpleado" HeaderText="Nombre empleado" SortExpression="nombreEmpleado" />
                <asp:BoundField DataField="primerApellido" HeaderText="Primer apellido" SortExpression="primerApellido" />
                <asp:BoundField DataField="segundoApellido" HeaderText="Segundo apellido" SortExpression="segundoApellido" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
        
            <asp:SqlDataSource ID="catEmpleados" runat="server" ConnectionString="<%$ ConnectionStrings:VentaComputadorasConnectionString11 %>" SelectCommand="SELECT * FROM [catEmpleados]" UpdateCommand="UPDATE [catEmpleados] SET [codigoEmpleado] = @codigoEmpleado, [nombreEmpleado] = @nombreEmpleado, [primerApellido] = @primerApellido, [segundoApellido] = @segundoApellido" DeleteCommand="DELETE FROM [catEmpleados] WHERE [codigoEmpleado] = @codigoEmpleado"></asp:SqlDataSource>

        </div>

    <%--Catalogo marcas--%>

      <div class="container">
            <div ><h2>Catalogo de marcas</h2></div>
    

        <div class="form-group">
            <label>Código marca</label>
            <input type="number" min="0"  runat="server" class="form-control" placeholder="Código marca" id="txtCodMarca" />
        </div>
        <div class="form-group">
            <label>Marca </label>
            <input type="text"  runat="server" class="form-control" placeholder="Marca" id="txtMarca" />
        </div>
        <div class="form-group">
            <label>Descripción</label>
            <input type="text"  runat="server" class="form-control" placeholder="Descripción" id="txtDescripcion" />
        </div>
          <br />
         <div class="form-group">
             <asp:Button ID="btnGuardarCatMarca" CssClass="btn btn-primary" runat="server" Text="Guardar" OnClick="btnGuardarCatMarca_Click" />
        </div>
      <br />
          <br />
        <asp:GridView ID="dtgMarcas" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CssClass="table table-bordered" DataKeyNames="codigoMarca" DataSourceID="catMarca" OnSelectedIndexChanged="dtgMarcas_SelectedIndexChanged" ToolTip="Muestra infromación del catálogo marcas de la bd" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
                <asp:BoundField DataField="codigoMarca" HeaderText="codigoMarca" ReadOnly="True" SortExpression="codigoMarca" />
                <asp:BoundField DataField="Marca" HeaderText="Marca" SortExpression="Marca" />
                <asp:BoundField DataField="Descripción" HeaderText="Descripción" SortExpression="Descripción" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>

            <asp:SqlDataSource ID="catMarca" runat="server" ConnectionString="<%$ ConnectionStrings:VentaComputadorasConnectionString11 %>" SelectCommand="SELECT * FROM [catMarcas]" DeleteCommand="DELETE FROM [catMarcas] WHERE [codigoMarca] = @codigoMarca" UpdateCommand="UPDATE [catMarcas] SET [codigoMarca] = @codigoMarca, [Marca] = @Marca, [Descripción] = @Descripción WHERE [codigoMarca] = @codigoMarca"></asp:SqlDataSource>

        </div>


<%--        catálogo categorías--%>

    <div class="container">
            <div ><h2>Catalogo categorías</h2></div>
    

        <div class="form-group">
            <label>Código categorías</label>
            <input type="number" id="txtCodCategoria" runat="server" placeholder="Código categorías" class="form-control"  />
        </div>
        <div class="form-group">
            <label>Nombre categoría </label>
            <input type="text" id="txtCategoria" runat="server" placeholder="Nombre categorías" class="form-control" />
        </div>
        <div class="form-group">
            <label>Descripción</label>
            <input type="text" id="txtDescripcionCat" runat="server" placeholder="Descripción categoría" class="form-control" />
        </div>
      
        <asp:Button ID="btnGuardarCatCat" Text="Guardar" runat="server" CssClass="btn btn-primary" OnClick="btnGuardarCatCat_Click" />
        <br />
        <asp:GridView ID="dtgMostrarCate" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" CssClass="table table-condensed" DataKeyNames="codigoCategoria" DataSourceID="catCat" ForeColor="Black" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
                <asp:BoundField DataField="codigoCategoria" HeaderText="Código Categoría" ReadOnly="True" SortExpression="codigoCategoria" />
                <asp:BoundField DataField="nombreCategoria" HeaderText="Nombre categoría" SortExpression="nombreCategoria" />
                <asp:BoundField DataField="Descripcion" HeaderText="Descripción" SortExpression="Descripcion" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
            <asp:SqlDataSource ID="catCat" runat="server" ConnectionString="<%$ ConnectionStrings:VentaComputadorasConnectionString11 %>" SelectCommand="SELECT * FROM [catCategorias]" DeleteCommand="DELETE FROM [catCategorias] WHERE [codigoCategoria] = @codigoCategoria" UpdateCommand="UPDATE [catCategorias] SET [codigoCategoria] = @codigoCategoria, [nombreCategoria] = @nombreCategoria, [Descripcion] = @Descripcion WHERE [codigoCategoria] = @codigoCategoria"></asp:SqlDataSource>
        </div>

    <%--catálogo de proveedores--%>

    <div class="container">
            <div ><h2>Catálogo Proveedores</h2></div>
    

        <div class="form-group">
            <label>Código proveedor</label>
            <input id="txtCodProveedor" runat="server" type="number" class="form-control" placeholder="Código proveedor" />
        </div>
        <div class="form-group">
            <label>Nombre empresa </label>
            <input id="txtNombreEmpresa" runat="server" type="text" class="form-control" placeholder="Nombre empresa" />
        </div>
        <div class="form-group">
            <label>Teléfono</label>
            <input id="txtTelefono" runat="server" type="tel" class="form-control" placeholder="Teléfono" maxlength="10" />
        </div>
         <div class="form-group">
            <label>Ciudad</label>
            <input id="txtCiudad" runat="server" type="text" class="form-control" placeholder="Ciudad" />
        </div>
        <div class="form-group">
            <label>Departamento</label>
            <input id="txtDepartamento" runat="server" type="text" class="form-control" placeholder="Departamento" />
        </div>
      
        <asp:Button ID="btnGuardarProveedor" runat="server" Text="Guardar" CssClass="btn btn-primary" ToolTip="Guarda en la tabla de proveedores" OnClick="btnGuardarProveedor_Click" />
        <br />
        <asp:GridView ID="dtgProveedore" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CssClass="table table-condensed" DataKeyNames="codigoProveedor" DataSourceID="catProveedor" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
                <asp:BoundField DataField="codigoProveedor" HeaderText="codigoProveedor" ReadOnly="True" SortExpression="codigoProveedor" />
                <asp:BoundField DataField="nombreEmpresa" HeaderText="nombreEmpresa" SortExpression="nombreEmpresa" />
                <asp:BoundField DataField="Telefono" HeaderText="Telefono" SortExpression="Telefono" />
                <asp:BoundField DataField="Ciudad" HeaderText="Ciudad" SortExpression="Ciudad" />
                <asp:BoundField DataField="Departamento" HeaderText="Departamento" SortExpression="Departamento" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>

        
        

            <asp:SqlDataSource ID="catProveedor" runat="server" ConnectionString="<%$ ConnectionStrings:VentaComputadorasConnectionString11 %>" SelectCommand="SELECT * FROM [catProveedores]" DeleteCommand="DELETE FROM [catProveedores] WHERE [codigoProveedor] = @codigoProveedor" UpdateCommand="UPDATE [catProveedores] SET [codigoProveedor] = @codigoProveedor, [nombreEmpresa] = @nombreEmpresa, [Telefono] = @Telefono, [Ciudad] = @Ciudad, [Departamento] = @Departamento WHERE [codigoProveedor] = @codigoProveedor"></asp:SqlDataSource>

        
        

        </div>

        <%--catalogo bodegas--%>

    <div class="container">
            <div ><h2>Catálogo bodegas</h2></div>
  

        <div class="form-group">
            <label>Código bodegas</label>
            <input type="number" min="0" id="txtBodegaCodigo" class="form-control" placeholder="Código bodega" runat="server" />
        </div>
        <div class="form-group">
            <label>Nombre bodega </label>
            <input type="text" id="txtBodega" runat="server" placeholder="Bodega" class="form-control" />
        </div>
        <br />
        <asp:Button runat="server" ID="btnGuardarBodega" CssClass="btn btn-primary" text="Guardar" OnClick="btnGuardarBodega_Click"/>
        <asp:GridView ID="dtgBodega" CssClass="table table-bordered" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" DataKeyNames="idBodega" DataSourceID="catBodega" ForeColor="Black" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
                <asp:BoundField DataField="idBodega" HeaderText="idBodega" ReadOnly="True" SortExpression="idBodega" />
                <asp:BoundField DataField="nombreBodega" HeaderText="nombreBodega" SortExpression="nombreBodega" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
        
            <asp:SqlDataSource ID="catBodega" runat="server" ConnectionString="<%$ ConnectionStrings:VentaComputadorasConnectionString11 %>" SelectCommand="SELECT * FROM [catBodega]" DeleteCommand="DELETE FROM [catBodega] WHERE [idBodega] = @idBodega" UpdateCommand="UPDATE [catBodega] SET [idBodega] = @idBodega, [nombreBodega] = @nombreBodega WHERE [idBodega] = @idBodega"></asp:SqlDataSource>

        </div>
        </asp:Content>
