<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="catBodegas.aspx.cs" Inherits="CapaPresentacion.catBodegas" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <div class="container">
            <div ><h2>Catálogo bodegas</h2></div>
  

        <div class="form-group">
            <label>Código bodegas</label>
            <input type="number" min="0" id="txtBodegaCodigo" class="form-control" placeholder="Código bodega" runat="server" />
        </div>
        <div class="form-group">
            <label>Nombre bodega </label>
            <input type="text" id="txtBodega" runat="server" placeholder="Bodega" class="form-control" />
        </div>
        <br />
        <asp:Button runat="server" ID="btnGuardarBodega" CssClass="btn btn-primary" text="Guardar" OnClick="btnGuardarBodega_Click"/>
        <asp:GridView ID="dtgBodega" CssClass="table table-bordered" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" DataKeyNames="idBodega" DataSourceID="catBodega" ForeColor="Black" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
                <asp:BoundField DataField="idBodega" HeaderText="idBodega" ReadOnly="True" SortExpression="idBodega" />
                <asp:BoundField DataField="nombreBodega" HeaderText="nombreBodega" SortExpression="nombreBodega" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
        
            <asp:SqlDataSource ID="catBodega" runat="server" ConnectionString="<%$ ConnectionStrings:VentaComputadorasConnectionString11 %>" SelectCommand="SELECT * FROM [catBodega]" DeleteCommand="DELETE FROM [catBodega] WHERE [idBodega] = @idBodega" UpdateCommand="UPDATE [catBodega] SET [idBodega] = @idBodega, [nombreBodega] = @nombreBodega WHERE [idBodega] = @idBodega"></asp:SqlDataSource>

        </div>
</asp:Content>
