<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="catCategoria.aspx.cs" Inherits="CapaPresentacion.catCategoria" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
            <div ><h2>Catalogo categorías</h2></div>
    

        <div class="form-group">
            <label>Código categorías</label>
            <input type="number" id="txtCodCategoria" runat="server" placeholder="Código categorías" class="form-control"  />
        </div>
        <div class="form-group">
            <label>Nombre categoría </label>
            <input type="text" id="txtCategoria" runat="server" placeholder="Nombre categorías" class="form-control" />
        </div>
        <div class="form-group">
            <label>Descripción</label>
            <input type="text" id="txtDescripcionCat" runat="server" placeholder="Descripción categoría" class="form-control" />
        </div>
      
        <asp:Button ID="btnGuardarCatCat" Text="Guardar" runat="server" CssClass="btn btn-primary" OnClick="btnGuardarCatCat_Click" />
        <br />
        <asp:GridView ID="dtgMostrarCate" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" CssClass="table table-condensed" DataKeyNames="codigoCategoria" DataSourceID="catCat" ForeColor="Black" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
                <asp:BoundField DataField="codigoCategoria" HeaderText="Código Categoría" ReadOnly="True" SortExpression="codigoCategoria" />
                <asp:BoundField DataField="nombreCategoria" HeaderText="Nombre categoría" SortExpression="nombreCategoria" />
                <asp:BoundField DataField="Descripcion" HeaderText="Descripción" SortExpression="Descripcion" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
            <asp:SqlDataSource ID="catCat" runat="server" ConnectionString="<%$ ConnectionStrings:VentaComputadorasConnectionString11 %>" SelectCommand="SELECT * FROM [catCategorias]" DeleteCommand="DELETE FROM [catCategorias] WHERE [codigoCategoria] = @codigoCategoria" UpdateCommand="UPDATE [catCategorias] SET [codigoCategoria] = @codigoCategoria, [nombreCategoria] = @nombreCategoria, [Descripcion] = @Descripcion WHERE [codigoCategoria] = @codigoCategoria"></asp:SqlDataSource>
        </div>

</asp:Content>
