<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="catEmpleados.aspx.cs" Inherits="CapaPresentacion.catEmpleados" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
            <div ><h2>Catalogo empleados</h2></div>
    

        <div class="form-group">
            <label>Código empleado</label>
            <asp:TextBox ID="txtCodEmpleado" runat="server" CssClass="form-control" placeholder="Código empleado"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Nombre empleado </label>
            <asp:TextBox ID="txtNombreEmpleado" runat="server" placeholder="Nombre empleado" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Primer apellido</label>
            <asp:TextBox ID="txtPrimerApellido" runat="server" placeholder="Primer apellido" CssClass="form-control"></asp:TextBox>
        </div>
         <div class="form-group">
            <label>Segundo apellido</label>
            <asp:TextBox ID="txtSegundoApellido" runat="server" placeholder="Segundo apellido" CssClass="form-control"></asp:TextBox>
        </div>
      
        <asp:Button ID="btnGuardarEmpleado" CssClass="btn btn-primary" runat="server" Text="Guardar" OnClick="btnGuardarEmpleado_Click" />

        <asp:GridView ID="dtgCatEMpleados" CssClass="table table-bordered" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" DataKeyNames="codigoEmpleado" DataSourceID="catEmpleados" ForeColor="Black" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
                <asp:BoundField DataField="codigoEmpleado" HeaderText="Código empleado" ReadOnly="True" SortExpression="codigoEmpleado" />
                <asp:BoundField DataField="nombreEmpleado" HeaderText="Nombre empleado" SortExpression="nombreEmpleado" />
                <asp:BoundField DataField="primerApellido" HeaderText="Primer apellido" SortExpression="primerApellido" />
                <asp:BoundField DataField="segundoApellido" HeaderText="Segundo apellido" SortExpression="segundoApellido" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
        
            <asp:SqlDataSource ID="catEmpleados" runat="server" ConnectionString="<%$ ConnectionStrings:VentaComputadorasConnectionString11 %>" SelectCommand="SELECT * FROM [catEmpleados]" UpdateCommand="UPDATE [catEmpleados] SET [codigoEmpleado] = @codigoEmpleado, [nombreEmpleado] = @nombreEmpleado, [primerApellido] = @primerApellido, [segundoApellido] = @segundoApellido" DeleteCommand="DELETE FROM [catEmpleados] WHERE [codigoEmpleado] = @codigoEmpleado"></asp:SqlDataSource>

        </div>
</asp:Content>
