<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="catMarcas.aspx.cs" Inherits="CapaPresentacion.catMarcas" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
            <div ><h2>Catalogo de marcas</h2></div>
    

        <div class="form-group">
            <label>Código marca</label>
            <input type="number" min="0"  runat="server" class="form-control" placeholder="Código marca" id="txtCodMarca" />
        </div>
        <div class="form-group">
            <label>Marca </label>
            <input type="text"  runat="server" class="form-control" placeholder="Marca" id="txtMarca" />
        </div>
        <div class="form-group">
            <label>Descripción</label>
            <input type="text"  runat="server" class="form-control" placeholder="Descripción" id="txtDescripcion" />
        </div>
          <br />
         <div class="form-group">
             <asp:Button ID="btnGuardarCatMarca" CssClass="btn btn-primary" runat="server" Text="Guardar" OnClick="btnGuardarCatMarca_Click" />
        </div>
      <br />
          <br />
        <asp:GridView ID="dtgMarcas" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CssClass="table table-bordered" DataKeyNames="codigoMarca" DataSourceID="catMarca" OnSelectedIndexChanged="dtgMarcas_SelectedIndexChanged" ToolTip="Muestra infromación del catálogo marcas de la bd" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
                <asp:BoundField DataField="codigoMarca" HeaderText="codigoMarca" ReadOnly="True" SortExpression="codigoMarca" />
                <asp:BoundField DataField="Marca" HeaderText="Marca" SortExpression="Marca" />
                <asp:BoundField DataField="Descripción" HeaderText="Descripción" SortExpression="Descripción" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>

            <asp:SqlDataSource ID="catMarca" runat="server" ConnectionString="<%$ ConnectionStrings:VentaComputadorasConnectionString11 %>" SelectCommand="SELECT * FROM [catMarcas]" DeleteCommand="DELETE FROM [catMarcas] WHERE [codigoMarca] = @codigoMarca" UpdateCommand="UPDATE [catMarcas] SET [codigoMarca] = @codigoMarca, [Marca] = @Marca, [Descripción] = @Descripción WHERE [codigoMarca] = @codigoMarca"></asp:SqlDataSource>

        </div>

</asp:Content>
