<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="catProveedores.aspx.cs" Inherits="CapaPresentacion.catProveedores" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
            <div ><h2>Catálogo Proveedores</h2></div>
    

        <div class="form-group">
            <label>Código proveedor</label>
            <input id="txtCodProveedor" runat="server" type="number" class="form-control" placeholder="Código proveedor" />
        </div>
        <div class="form-group">
            <label>Nombre empresa </label>
            <input id="txtNombreEmpresa" runat="server" type="text" class="form-control" placeholder="Nombre empresa" />
        </div>
        <div class="form-group">
            <label>Teléfono</label>
            <input id="txtTelefono" runat="server" type="tel" class="form-control" placeholder="Teléfono" maxlength="10" />
        </div>
         <div class="form-group">
            <label>Ciudad</label>
            <input id="txtCiudad" runat="server" type="text" class="form-control" placeholder="Ciudad" />
        </div>
        <div class="form-group">
            <label>Departamento</label>
            <input id="txtDepartamento" runat="server" type="text" class="form-control" placeholder="Departamento" />
        </div>
      
        <asp:Button ID="btnGuardarProveedor" runat="server" Text="Guardar" CssClass="btn btn-primary" ToolTip="Guarda en la tabla de proveedores" OnClick="btnGuardarProveedor_Click" />
        <br />
        <asp:GridView ID="dtgProveedore" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CssClass="table table-condensed" DataKeyNames="codigoProveedor" DataSourceID="catProveedor" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
                <asp:BoundField DataField="codigoProveedor" HeaderText="codigoProveedor" ReadOnly="True" SortExpression="codigoProveedor" />
                <asp:BoundField DataField="nombreEmpresa" HeaderText="nombreEmpresa" SortExpression="nombreEmpresa" />
                <asp:BoundField DataField="Telefono" HeaderText="Telefono" SortExpression="Telefono" />
                <asp:BoundField DataField="Ciudad" HeaderText="Ciudad" SortExpression="Ciudad" />
                <asp:BoundField DataField="Departamento" HeaderText="Departamento" SortExpression="Departamento" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>

        
        

            <asp:SqlDataSource ID="catProveedor" runat="server" ConnectionString="<%$ ConnectionStrings:VentaComputadorasConnectionString11 %>" SelectCommand="SELECT * FROM [catProveedores]" DeleteCommand="DELETE FROM [catProveedores] WHERE [codigoProveedor] = @codigoProveedor" UpdateCommand="UPDATE [catProveedores] SET [codigoProveedor] = @codigoProveedor, [nombreEmpresa] = @nombreEmpresa, [Telefono] = @Telefono, [Ciudad] = @Ciudad, [Departamento] = @Departamento WHERE [codigoProveedor] = @codigoProveedor"></asp:SqlDataSource>

        
        

        </div>

</asp:Content>
