<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="facturacion.aspx.cs" Inherits="CapaPresentacion.facturacion" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div class="container"><h1>Ventas</h1>
        <div class="form-group">
            <label>Código de ventas</label>
            <input type="number" id="txtCodVentas" runat="server" class="form-control" placeholder="Código de ventas"/>
        </div>
        <div class="form-group">
            <label>Fecha de venta</label>
            <input type="date" id="txtFecha" class="form-control" runat="server" />
            
           
        </div>
        <div class="form-group">
            <label>Nombre cliente</label>
            <input type="text" id="txtNombreCliente" class="form-control" runat="server" placeholder="Nombre de cliente" />
        </div>
        <div class="form-group">
            <label>Subtotal</label>          
            <input type="number" min="0" id="txtSubtotal" class="form-control" placeholder="Subtotal" runat="server" />
        </div>
        <div class="form-group">
            <label>I.V.A</label>
            <input type="number" runat="server" placeholder="Impuesto de valor agregado" id="txtIVA" class="form-control" readonly="True"/>
        </div>
        <div class="form-group">
            <label>Descuento</label>
            <input type="number"  min="0" runat="server" placeholder="Descuento" id="txtDescuento" class="form-control" readonly="True" />
        </div>
        <div class="form-group">
            <label>Total</label>
            <input type="number" min="0" runat="server" placeholder="Total" id="txtTotalVenta" class="form-control" readonly="True"/>
        </div>
        <div class="form-group">
            <label>ID empleado</label>
            <asp:DropDownList ID="drIdEmpleado" runat="server" CssClass="form-control" DataSourceID="drCatEmpleado" DataTextField="codigoEmpleado" DataValueField="codigoEmpleado"></asp:DropDownList>
            <asp:SqlDataSource ID="drCatEmpleado" runat="server" ConnectionString="<%$ ConnectionStrings:VentaComputadorasConnectionString11 %>" SelectCommand="SELECT * FROM [catEmpleados]"></asp:SqlDataSource>
        </div>
        <asp:Button ID="btnAgregarVenta" CssClass="btn btn-primary" runat="server" Text="Guardar" OnClick="btnAgregarVenta_Click" />

        <br />
        <asp:GridView ID="dtgTablaVenta" CssClass="table table-bordered" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="codigoVentas" DataSourceID="tabalaVenta" ForeColor="Black" GridLines="Horizontal">
            <Columns>
                <asp:BoundField DataField="codigoVentas" HeaderText="codigoVentas" ReadOnly="True" SortExpression="codigoVentas" />
                <asp:BoundField DataField="FechaVenta" HeaderText="FechaVenta" SortExpression="FechaVenta" />
                <asp:BoundField DataField="Cliente" HeaderText="Cliente" SortExpression="Cliente" />
                <asp:BoundField DataField="Subtotal" HeaderText="Subtotal" SortExpression="Subtotal" />
                <asp:BoundField DataField="IVA" HeaderText="IVA" SortExpression="IVA" />
                <asp:BoundField DataField="Descuento" HeaderText="Descuento" SortExpression="Descuento" />
                <asp:BoundField DataField="Total" HeaderText="Total" SortExpression="Total" />
                <asp:BoundField DataField="idEmpleado" HeaderText="idEmpleado" SortExpression="idEmpleado" />
            </Columns>
            <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
            <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
            <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#242121" />
        </asp:GridView>


        <asp:SqlDataSource ID="tabalaVenta" runat="server" ConnectionString="<%$ ConnectionStrings:VentaComputadorasConnectionString11 %>" SelectCommand="SELECT * FROM [tblVentas]" DeleteCommand="DELETE FROM [tblVentas] WHERE [codigoVentas] = @codigoVentas" UpdateCommand="UPDATE [tblVentas] SET [codigoVentas] = @codigoVentas, [FechaVenta] = @FechaVenta, [Cliente] = @Cliente, [Subtotal] = Subtotal, [Descuento] = @Descuento, [Total] = @Total, [idEmpleado] = @idEmpleado WHERE [codigoVentas] = @codigoVentas"></asp:SqlDataSource>

    </div>


    <%--ventas--%>


    <div class="container"><h1>Tabla compras</h1>
        <div class="form-group">
            <label>Código de compras</label>
            <input type="number" id="txtCodCompra" runat="server" class="form-control" placeholder="Código de compras"/>
        </div>
        <div class="form-group">
            <label>Fecha de compra</label>
            <input type="date" id="txtFechaCompra" class="form-control" runat="server" />
            
           
        </div>
         <div class="form-group">
            <label>ID empleado</label>
            <asp:DropDownList ID="txtIdEmpleadoCompra" runat="server" CssClass="form-control" DataSourceID="drCatEmpleado" DataTextField="codigoEmpleado" DataValueField="codigoEmpleado"></asp:DropDownList>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:VentaComputadorasConnectionString11 %>" SelectCommand="SELECT * FROM [catEmpleados]"></asp:SqlDataSource>
        </div>
        <div class="form-group">
            <label>Subtotal</label>          
            <input type="number" min="0" id="txtSubtotalCompra" class="form-control" placeholder="Subtotal" runat="server" />
        </div>
        <div class="form-group">
            <label>I.V.A</label>
            <input type="number" runat="server" readonly="True" placeholder="Impuesto de valor agregado" id="txtIvaCompra" class="form-control" />
        </div>
        <div class="form-group">
            <label>Descuento</label>
            <input type="number"  min="0" runat="server" readonly="True" placeholder="Descuento" id="txtDescuentoCompra" class="form-control" />
        </div>
        <div class="form-group">
            <label>Total</label>
            <input type="number" min="0" runat="server" readonly="True" placeholder="Total" id="txtTotalCompra" class="form-control" />
        </div>
          <div class="form-group">
            <label>Id proveedor</label>
              <asp:DropDownList ID="txtIdProveedorCompra" CssClass="form-control" runat="server" DataSourceID="catProveedor" DataTextField="codigoProveedor" DataValueField="codigoProveedor"></asp:DropDownList>
              <asp:SqlDataSource ID="catProveedor" runat="server" ConnectionString="<%$ ConnectionStrings:VentaComputadorasConnectionString11 %>" SelectCommand="SELECT * FROM [catProveedores]"></asp:SqlDataSource>
        </div>
      
        <asp:Button ID="btnGuardarCompra" CssClass="btn btn-primary" runat="server" Text="Guardar" OnClick="btnGuardarCompra_Click"  />

        <br />
        <asp:GridView ID="dtgMostrarCompra" CssClass="table table-bordered" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="codigoCompra" DataSourceID="tblCompras" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
                <asp:BoundField DataField="codigoCompra" HeaderText="Codigo compra" ReadOnly="True" SortExpression="codigoCompra" />
                <asp:BoundField DataField="fechaCompra" HeaderText="Fecha compra" SortExpression="fechaCompra" />
                <asp:BoundField DataField="idEmpleado" HeaderText="Id empleado" SortExpression="idEmpleado" />
                <asp:BoundField DataField="Subtotal" HeaderText="Subtotal" SortExpression="Subtotal" />
                <asp:BoundField DataField="IVA" HeaderText="IVA" SortExpression="IVA" />
                <asp:BoundField DataField="Descuento" HeaderText="Descuento" SortExpression="Descuento" />
                <asp:BoundField DataField="Total" HeaderText="Total" SortExpression="Total" />
                <asp:BoundField DataField="idProveedor" HeaderText="Id proveedor" SortExpression="idProveedor" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
        </asp:GridView>
        <asp:SqlDataSource ID="tblCompras" runat="server" ConnectionString="<%$ ConnectionStrings:VentaComputadorasConnectionString11 %>" SelectCommand="SELECT * FROM [tblCompras]" DeleteCommand="DELETE FROM [tblCompras] WHERE [codigoCompra] = @codigoCompra" UpdateCommand="UPDATE [tblCompras] SET [codigoCompra] = @codigoCompra, [fechaCompra] = @fechaCompra, [idEmpleado] = @idEmpleado, [Subtotal] = @Subtotal, [IVA] = @IVA, [Descuento] = @Descuento, [Total] = @Total, [idProveedor] = @idProveedor WHERE [codigoCompra] = @codigoCompra"></asp:SqlDataSource>
        </div>






</asp:Content>
