//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class catArticulos
    {
        public catArticulos()
        {
            this.tblComprasDetalle = new HashSet<tblComprasDetalle>();
            this.tblProductosAlmacen = new HashSet<tblProductosAlmacen>();
            this.tblVentasDetalle = new HashSet<tblVentasDetalle>();
        }
    
        public int codigoArticulo { get; set; }
        public string nombreArticulo { get; set; }
        public int idCategoria { get; set; }
    
        public virtual catCategorias catCategorias { get; set; }
        public virtual ICollection<tblComprasDetalle> tblComprasDetalle { get; set; }
        public virtual ICollection<tblProductosAlmacen> tblProductosAlmacen { get; set; }
        public virtual ICollection<tblVentasDetalle> tblVentasDetalle { get; set; }
    }
}
