//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class catBodega
    {
        public catBodega()
        {
            this.tblProductosAlmacen = new HashSet<tblProductosAlmacen>();
        }
    
        public int idBodega { get; set; }
        public string nombreBodega { get; set; }
    
        public virtual ICollection<tblProductosAlmacen> tblProductosAlmacen { get; set; }
    }
}
