//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class catCategorias
    {
        public catCategorias()
        {
            this.catArticulos = new HashSet<catArticulos>();
        }
    
        public int codigoCategoria { get; set; }
        public string nombreCategoria { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<catArticulos> catArticulos { get; set; }
    }
}
