//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class catMarcas
    {
        public catMarcas()
        {
            this.tblComprasDetalle = new HashSet<tblComprasDetalle>();
            this.tblProductosAlmacen = new HashSet<tblProductosAlmacen>();
        }
    
        public int codigoMarca { get; set; }
        public string Marca { get; set; }
        public string Descripción { get; set; }
    
        public virtual ICollection<tblComprasDetalle> tblComprasDetalle { get; set; }
        public virtual ICollection<tblProductosAlmacen> tblProductosAlmacen { get; set; }
    }
}
