//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompras
    {
        public tblCompras()
        {
            this.tblComprasDetalle = new HashSet<tblComprasDetalle>();
        }
    
        public int codigoCompra { get; set; }
        public System.DateTime fechaCompra { get; set; }
        public int idEmpleado { get; set; }
        public decimal Subtotal { get; set; }
        public decimal IVA { get; set; }
        public decimal Descuento { get; set; }
        public decimal Total { get; set; }
        public int idProveedor { get; set; }
    
        public virtual catProveedores catProveedores { get; set; }
        public virtual ICollection<tblComprasDetalle> tblComprasDetalle { get; set; }
    }
}
