//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductosAlmacen
    {
        public int codigoArticuloBodega { get; set; }
        public decimal Costo { get; set; }
        public decimal precioVenta { get; set; }
        public int Existencia { get; set; }
        public string Lote { get; set; }
        public int idMarca { get; set; }
        public int idArticulo { get; set; }
        public int idBodega { get; set; }
        public int idCompra { get; set; }
        public string Descripcion { get; set; }
    
        public virtual catArticulos catArticulos { get; set; }
        public virtual catBodega catBodega { get; set; }
        public virtual catMarcas catMarcas { get; set; }
    }
}
